version: "3.7"
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    links:
      - backend
    working_dir: /app-frontend
    tty: true
    stdin_open: true

  backend:
    build: ./backend
    ports:
      - 8000:8000
    working_dir: /app-backend
    links:
      - db
    volumes:
      - ./backend/src:/app-backend/src
    tty: true
    stdin_open: true

volumes:
  mongodb_data_container:
