version: "3.7"
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    tty: true
    stdin_open: true
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - 8000:8000
    working_dir: /app-backend
    volumes:
      - ./backend/src:/app-backend/src
    tty: true
    stdin_open: true
    networks:
      - mynetwork

volumes:
  mongodb_data_container:

networks:
  mynetwork:
    driver: bridge
